server:
  port: 80
  context-path: /
spring:
  #MySQL
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/nocode
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
  #thymeleaf
  thymeleaf:
    prefix: classpath:/templates
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    cache: false
